version: "3"
services:
  db:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres10
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bookstore
    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: bookstoreapp:latest
    network_mode: bridge
    container_name: bookstoreapp
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
#volumes:
#  postgres-data: